- hosts: loadbalancer
  vars_prompt:
          - name: load_port
            prompt: "Enter the Port for the Load Balancer"
            private: no
  tasks:
          - package:
                  name: haproxy
                  state: present
          - template:
                  src: "/home/ansadmin/HAProxy_automation/template.cfg"
                  dest: "/etc/haproxy/haproxy.cfg"
          - service:
                  name: haproxy
                  state: started
                  enabled: yes

- hosts: targetserver
  tasks:
          - package:
                  name: httpd
                  state: present
          - package:
                  name: php
                  state: present
          - copy:
                  src: "/home/ansadmin/HAProxy_automation/index.php"
                  dest: "/var/www/html"
          - service:
                  name: httpd
                  state: started
                  enabled: yes
