- hosts: datanode
  vars:
          - destination: "/home/ansadmin"
          - hadoop_file: "hadoop-1.2.1-1.x86_64.rpm"
          - JVM_file: "jdk-8u171-linux-x64.rpm"
          - hadoop_core_file: ""
          - hadoop_path: "/etc/hadoop"
          - start_data: "hadoop-daemon.sh start datanode"
          - hdfs_name: "dfs.data.dir"
          - node: "data"
            # - format_name: "hadoop namenode -format"
  vars_prompt:
          - name: name_node_dir
            prompt: "Enter the directory for Data Node"
            private: no
          - name: ip_for_core
            prompt: "Enter the IP for Name node"
            private: no
  tasks:
          #- name: "Adding rpm file for Hadoop"
          #   copy:
          #         src: "{{ hadoop_file }}"
          #         dest: "{{ destination }}"
          # - name: "Adding rpm file for JVM"
          # copy:
          #         src: "{{ JVM_file }}"
          #         dest: "{{ destination }}"
                    #- name: "Installing JVM for Data Node"
                    # command: "rpm -ivh {{ JVM_file }}"

                  
                    #- name: "Installing Hadoop for Data Node"
                    # command: "rpm -ivh {{ hadoop_file }} --force"

          - name: "Setting up Hadoop Data node Directory"
            file:
                    state: directory
                    src: "/"
                    name: "{{ name_node_dir }}"


          - name: "Setting up core-site.xml"
            template:
                    dest: "{{ hadoop_path }}/core-site.xml"
                    src: "core-site.xml"

          - name: "Setting up HDFS_site.xml"
            template:
                    dest: "{{ hadoop_path }}/hdfs-site.xml"
                    src: "hdfs-site.xml"

                    # - name: "Formating Name node"
                    # shell: "echo Y | {{ format_name }}"

          - name: "Starting the Data node"
            command: "{{ start_data }}"

          - name: "Status of Data node"
            command: "jps"
            register: out
          - debug:
                  var: out.stdout


