- hosts: namenode
  vars:
          - destination: "/home/ansadmin"
          - hadoop_file: "hadoop-1.2.1-1.x86_64.rpm"
          - JVM_file: "jdk-8u171-linux-x64.rpm"
          - hadoop_core_file: ""
          - hadoop_path: "/etc/hadoop"
          - start_name: "hadoop-daemon.sh start namenode"
          - format_name: "hadoop namenode -format"
          - ip_for_core: "ansible_facts['default_ipv4']['address']"
          - hdfs_name: "dfs.name.dir"
          - node: "name"
  vars_prompt:
          - name: name_node_dir
            prompt: "Enter the directory for Name Node"
            private: no
          - name: name_node_ip
            prompt: "Enter the IP for name node"
            private: no
  tasks:
          - name: "Adding rpm file for Hadoop"
            copy:
                    src: "{{ hadoop_file }}"
                    dest: "{{ destination }}"
          - name: "Adding rpm file for JVM"
            copy:
                    src: "{{ JVM_file }}"
                    dest: "{{ destination }}"
                    # - name: "Installing JVM for Name Node"
                    # command: "rpm -ivh {{ JVM_file }}"
                    # register: java
                    #- debug:
                    # var: java.stdout

                    # - name: "Installing Hadoop for Name Node"
                    # command: "rpm -ivh {{ hadoop_file }} --force"

          - name: "Setting up Hadoop Name node Directory"
            file:
                    state: directory
                    src: "/"
                    name: "{{ name_node_dir }}"


          - name: "Setting up core-site.xml"
            template:
                    dest: "{{ hadoop_path }}/core-site.xml"
                    src: "master-core-site.xml"

          - name: "Setting up HDFS_site.xml"
            template:
                    dest: "{{ hadoop_path }}/hdfs-site.xml"
                    src: "hdfs-site.xml"

                    # - name: "Formating Name node"
                    # shell: "echo Y | {{ format_name }}"

          - name: "Starting the Name node"
            command: "{{ start_name }}"

          - name: "Status of Name node"
            command: "jps"
            register: out
          - debug:
                  var: out.stdout


